from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class OperatorChatConsoleStaticTests(unittest.TestCase):
    def test_operator_chat_console_ui_is_registered(self) -> None:
        ui = (ROOT / "app" / "ui.py").read_text(encoding="utf-8")

        self.assertIn('"chat","Chat Console",true', ui)
        self.assertIn("function chatConsole()", ui)
        self.assertIn("CHAT_HISTORY_STORAGE_KEY", ui)
        self.assertIn("CHAT_PREFERENCES_STORAGE_KEY", ui)
        self.assertIn("readChatPreferences", ui)
        self.assertIn("saveChatPreferences", ui)
        self.assertIn("applyChatPreferences", ui)
        self.assertIn("bindChatPreferenceEvents", ui)
        self.assertIn("CHAT_HISTORY_MAX_BYTES", ui)
        self.assertIn("CHAT_IMAGE_MAX_BYTES", ui)
        self.assertIn("CHAT_IMAGE_SOURCE_MAX_BYTES", ui)
        self.assertIn("5 * 1024 * 1024", ui)
        self.assertIn("12 * 1024 * 1024", ui)
        self.assertIn("Image input is limited to 5 MB.", ui)
        self.assertIn("clearChatImage();", ui)
        self.assertIn("compactChatSessionsForStorage", ui)
        self.assertNotIn("state.chatSessions = compactChatSessionsForStorage", ui)
        self.assertIn("handleChatPaste", ui)
        self.assertIn("handleChatDrop", ui)
        self.assertIn("compressChatImage", ui)
        self.assertIn("prepareChatImageFile", ui)
        self.assertIn('canvas.toDataURL("image/jpeg", 0.85)', ui)
        self.assertIn("localStorage", ui)
        self.assertIn("Clear history", ui)
        self.assertIn("Delete chat", ui)
        self.assertIn("chat-console-shell", ui)
        self.assertIn("chat-icon-button", ui)
        self.assertIn("chat-sidebar-actions", ui)
        self.assertIn("chat-composer-shell", ui)
        self.assertIn("chat-action-slot", ui)
        self.assertIn("handleChatInputKeydown", ui)
        self.assertIn('event.key === "Escape"', ui)
        self.assertIn('event.key === "Enter" && !event.shiftKey', ui)
        self.assertIn("state.chatIsGenerating", ui)
        self.assertIn("state.chatSendInFlight", ui)
        self.assertIn("event.repeat", ui)
        self.assertIn("event.isComposing", ui)
        self.assertIn("appendChatAssistantContent", ui)
        self.assertIn("content.startsWith(message.content)", ui)
        self.assertIn('title="Voice input"', ui)
        self.assertIn('title="Attach image"', ui)
        self.assertIn('aria-label="Send message"', ui)
        self.assertIn('aria-label="Stop generating"', ui)
        self.assertIn("stopChatConsoleGeneration", ui)
        self.assertIn("AbortController", ui)
        self.assertIn("TextDecoder", ui)
        self.assertIn('fetch("/api/admin/chat-test/message/stream"', ui)
        self.assertIn("appendChatAssistantDelta", ui)
        self.assertIn('aria-label="Delete chat"', ui)
        self.assertIn("chat-message-actions", ui)
        self.assertIn("copyChatMessage", ui)
        self.assertIn("deleteChatMessage", ui)
        self.assertIn('aria-label="Copy message"', ui)
        self.assertIn('aria-label="Delete message"', ui)
        self.assertIn("downloadCurrentChatMarkdown", ui)
        self.assertIn("downloadCurrentChatJson", ui)
        self.assertIn("chatMessagesMarkdown", ui)
        self.assertIn("chatSystemPrompt", ui)
        self.assertIn("buildChatRequestMessages", ui)
        self.assertIn('role: "system"', ui)
        self.assertIn("chatResponseLengthSelect", ui)
        self.assertIn("responseNumPredict", ui)
        self.assertIn("response_num_predict", ui)
        self.assertIn("num_predict", ui)
        self.assertIn("1024", ui)
        self.assertIn("Thinking", ui)
        self.assertIn("selectedModelLooksVisionCapable", ui)
        self.assertIn("updateChatVisionNotice", ui)
        self.assertIn("Image input", ui)
        self.assertIn("chatImageInput", ui)
        self.assertIn("chatImagePreview", ui)
        self.assertIn("startVoiceInput", ui)
        self.assertIn("SpeechRecognition", ui)
        self.assertIn('api("/api/admin/chat-test/models"', ui)
        self.assertIn('fetch("/api/admin/chat-test/message/stream"', ui)
        self.assertIn("buildChatRequestMessages(session, assistantMessage)", ui)

    def test_operator_chat_console_api_is_admin_guarded(self) -> None:
        route = (ROOT / "app" / "chat_console_routes.py").read_text(encoding="utf-8")
        main = (ROOT / "app" / "main.py").read_text(encoding="utf-8")

        self.assertIn("current_admin", route)
        self.assertIn('prefix="/api/admin/chat-test"', route)
        self.assertIn('"/models"', route)
        self.assertIn('"/message"', route)
        self.assertIn('"/api/tags"', route)
        self.assertIn('"/api/chat"', route)
        self.assertIn('"/message/stream"', route)
        self.assertIn("StreamingResponse", route)
        self.assertIn('"stream": True', route)
        self.assertIn("aiter_lines", route)
        self.assertIn('"think": payload.thinking_enabled', route)
        self.assertIn("response_num_predict", route)
        self.assertIn('"options": {"num_predict": payload.response_num_predict}', route)
        self.assertIn("images: list[str]", route)
        self.assertIn('messages[index]["images"] = payload.images', route)
        self.assertNotIn('"images": payload.images', route)
        self.assertIn("chat_console_router", main)


if __name__ == "__main__":
    unittest.main()
